# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'demoSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Elegant HTTP Networking in Swift
  # - Homepage: https://github.com/Alamofire/Alamofire
  pod 'Alamofire', '~> 5.8.0'

end
